@ECHO OFF
TITLE JSK Bot
CHOICE /M "Do you really want to start the bot?"
ECHO Bat Starting...
TITLE JSK Bot, Starting...
ECHO Scripts Starting...
TITLE JSK Bot, Scripts Starting...
ECHO Bot Starting...
TITLE JSK Bot, Bot Starting...
ECHO Done! Now loading...
TITLE JSK Bot, Done! Loading now!
TITLE JSK Bot, successfully loaded!
TITLE JSK Bot

cd C:\Users\Knight Mackay\Desktop\discordbot\Scripts
node main.js
cd C:\Users\Knight Mackay\Desktop\discordbot\Discord-Auto-Publisher-master
node bot.js